### ISSUE TITLE
Feat: PDF-Darstellung

### ISSUE THREAD

**Issue by JuliaSageder** [UniRegensburg/basisdokument#15]
**Beschreibung des Features**
Formatierung und Aussehen der PDF-Version soll weiter verbessert werden. Dazu kam am 09.03.23 noch die mögliche Anforderung die Darstellungsweise im PDF der Dialog-Darstellung im Basisdokument anzupassen. Dies könnte vielleicht über Abstände/Kästen o.ä. angedeutet werden - was es da für Möglichkeiten gibt muss aber erst noch geprüft werden. Möglicherweise könnte in einem Abschlussdialog vor dem Herunterladen (vgl. Issue #8) eine Darstellungsweise im PDF gewählt werden? Dies wird im JourFixe am 13.03.23 weiter diskutiert und dann nochmals ergänzt.

**Akzeptanzkriterien**
- [x] Prüfen wie (gut) die Möglichkeiten der Darstellung bei Erzeugung des PDFs beeinflusst werden kann

weitere Anforderungen durch den Termin in der Geschäftsstelle:
- [x] Zusammenfassung/Überblick der neuesten Änderungen auf eigener Seite
- [x] verlinkte Gliederung im/des PDF-Dokuments
- [x] Änderungen visuell hervorheben ("Neu" + Rahmenfarbe)
- [x] Einzelexport von Teilen des PDF (Kläger/Beklagter, einzelne Gliederungspunkte, einzelne Beiträge) (Export-Dialog, vgl. Issue #8 )
- [x] Seitenzahlen
- [x] Möglichkeit Bearbeitungsnamen in der Signatur anzupassen (Export-Dialog, vgl. Issue #8 )
- [x] Möglichkeit Betreff für die Version des PDF hinzuzufügen (aufgeführt auf der ersten Seite bei den Metadaten zum Basisdokument) (Export-Dialog, vgl. Issue #8 )
- [x] Hinweise auf eigene Seite(n)
- [x] Neue Hinweise hervorheben ("Neuer Hinweis" + Rahmenfarbe)
- [x] Hinweise nochmal als Kommentar umgewandelt an die verknüpfte Stelle ins PDF
- [ ] #133
- [x] KV und BKV (und R?) in den Exportnamen (klarer WER neue Version einreicht) (verworfen, Änderung ist wäre zu spät im Projekt und würde Nutzer voraussichtlich verwirren)
- [x] (Export-)Datum in die Beiträge integrieren (wie in der Browser-Ansicht)
- [x] Hinweis/Zeile auf Original-Beitrag in die beitragsbezogenen Beiträge

warten auf weitere Anforderungen von Seiten Hannover/Osnabrück

**Comment by JuliaSageder** [comment]
Einarbeitung/Recherche wg Option auf neuen PDF-Generator ist im Gange, alles umzubauen auf einen neuen Generator scheint mir nicht nötig zu sein, da jsPDF mehr Optionen bietet als angenommen (vgl. https://mrrio.github.io/jsPDF/examples/basic.html und https://rawgit.com/MrRio/jsPDF/master/docs/index.html)

**Comment by JuliaSageder** [comment]
Nutzung eines weiteren Plugin zusätzlich zu jspdf: jspdf autotable um die Daten besser strukturieren zu können

**Comment by JuliaSageder** [comment]
für letzte Änderung siehe #133
